#!/usr/bin/env bash

rm -rf prime/*
rm -rf parts/*
rm -rf stage/*
rm -f *.snap

snapcraft clean
snapcraft prime

# reduce size
rm -f prime/usr/lib/x86_64-linux-gnu/libLLVM*
rm -f prime/usr/lib/x86_64-linux-gnu/libx265.so.79
rm -f prime/usr/lib/x86_64-linux-gnu/libflite*
rm -f prime/usr/lib/x86_64-linux-gnu/dri/*

snapcraft
sync
