base: core18
name: phockup
grade: stable
confinement: strict
adopt-info: set-version
summary: Photo and video sorting tool
description: |
  Media sorting tool to organize photos and videos from your camera in folders by year, month and day.
  The software will collect all files from the input directory and copy them to the output directory without
  changing the files content. It will only rename the files and place them in the proper directory for year, month and day.

apps:
  phockup:
    command: phockup.sh
    plugs: [home, removable-media, raw-usb]

parts:
  set-version:
    plugin: nil
    source: .
    override-pull: |
      snapcraftctl pull
      VERSION=`cat phockup.py | grep '__version__ = ' | sed sed "s/.*'\(.*\)'/\1/"`
      snapcraftctl set-version $VERSION

  files:
    plugin: dump
    source: .
    stage-packages:
      - locales-all
      - python3
      - libimage-exiftool-perl
